### ISSUE TITLE
Improve the explodePath by doing the regex in a non-greedy way in one go.

### ISSUE THREAD

**Issue by robertdumitrescu** [robertdumitrescu/collection-path-helper#2]
As a library user, I would want to have a hasty library to manipulate collection paths on the fly and when I churn through object properties maintaining a state cursor, in order to achieve better processing times overall and lower costs in applications like Spark/Hive or any other ad-hoc processing system.

Currently, explodePath (complex path) (1) does 217456.7 ops/s. We should improve that since is one of the backbone operations of the library. You improve the speed of that, you improve the speed of the whole library.

**Comment by practiseo** [comment]
Done
